import { chromium } from '@playwright/test';
import { tools } from '../src/toolCatalog.js';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173/auth');await page.getByLabel('Full name').fill('Route QA');await page.getByLabel('Email address').fill('routes-'+Date.now()+'@example.com');await page.getByLabel('Password',{exact:true}).fill('route-private-password');await page.getByRole('button',{name:'Create my space'}).click();await page.waitForURL('**/dashboard');
for(const width of [1440,390]){await page.setViewportSize({width,height:950});for(const tool of tools){await page.goto('http://127.0.0.1:5173/dashboard/'+tool.id);await page.locator('.workspace-page-heading, .overview-heading').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,tool.id+' overflows at '+width);}console.log('All '+tools.length+' tool routes passed at '+width+'px');}
await page.goto('http://127.0.0.1:5173/dashboard/groups');await page.getByLabel('Group name').fill('Physics circle');await page.getByRole('button',{name:'Create group',exact:true}).click();await page.getByLabel('Invitation code',{exact:true}).first().waitFor();
await page.goto('http://127.0.0.1:5173/dashboard/announcements');await page.getByRole('button',{name:'New update'}).click();await page.getByLabel('Title',{exact:true}).fill('Welcome to our circle');await page.getByLabel('Audience').fill('All members');await page.getByLabel('Details').fill('Our first revision session is on Friday.');await page.getByRole('button',{name:'Publish to group'}).click();await page.getByRole('heading',{name:'Welcome to our circle'}).waitFor();await page.getByRole('button',{name:'Mark as read'}).click();await page.getByRole('button',{name:'Read — undo'}).waitFor();await page.screenshot({path:'work/qa/mobile-announcements.png',fullPage:true});
await page.goto('http://127.0.0.1:5173/dashboard/skills');await page.getByLabel('Where do you want to go?').fill('Frontend developer');await page.getByLabel('New milestone').fill('Build an accessible form');await page.getByRole('button',{name:'Add milestone'}).click();await page.getByRole('button',{name:'Save my path'}).click();await page.locator('.saved-row').waitFor();
for(const path of ['/','/about','/features','/use-cases','/solutions','/integrations','/blog']){await page.goto('http://127.0.0.1:5173'+path);await page.waitForTimeout(550);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'Public '+path+' overflows');}
console.log('Public mobile pages and group/path workflows passed. Errors:',errors);assert.deepEqual(errors,[]);await browser.close();
