import QuoteCard from './QuoteCard';
import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowUpRight,Eye,EyeOff,Leaf,ShieldCheck,BookOpen} from 'lucide-react';
import {api} from './api';
export default function Account(){
 const [mode,setMode]=useState('signup'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false);
 const navigate=useNavigate();
 useEffect(()=>{api('/me').then(()=>navigate('/dashboard',{replace:true})).catch(()=>{});},[]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{await api('/'+mode,{method:'POST',body:data});navigate('/dashboard',{replace:true});}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="account-page"><section className="account-story"><Link to="/" className="brand brand-light"><span className="logo-mark"><span/></span>nxtgen</Link><div><p className="overline">A LITTLE CURIOSITY. A WORLD OF POSSIBILITY.</p><h1>Your space.<br/> Your pace.<br/><em>Your next chapter.</em></h1><p>Gather your ideas, find your focus, and make room for what comes next.</p></div><div className="account-illustration"><div className="account-orbit"/><div className="account-leaf"><Leaf size={96} strokeWidth={1}/></div><span className="floating-note"><BookOpen size={20}/> One idea at a time.</span></div><p className="account-foot">Designed for a mind like yours. <span>✦</span></p></section><section className="account-form-side"><Link to="/" className="back-link">← Back to NxtGen</Link><div className="account-form-inner"><div className="account-switch">{['signup','login'].map(m=><button key={m} className={mode===m?'active':''} onClick={()=>{setMode(m);setError('');}}>{m==='signup'?'Create account':'Log in'}</button>)}</div><p className="overline">YOUR PERSONAL LEARNING SPACE</p><h2>{mode==='signup'?'A fresh beginning.':'Welcome back.'}</h2><p>{mode==='signup'?'A few details, then make yourself at home.':'Your ideas are right where you left them.'}</p><form onSubmit={submit} key={mode}>{mode==='signup'&&<label>Full name<input autoComplete="name" name="name" placeholder="Your name" required maxLength={80}/></label>}<label>Email address<input type="email" name="email" placeholder="you@example.com" autoComplete="email" required/></label><label>Password<div className="password-wrap"><input name="password" type={show?'text':'password'} minLength={10} maxLength={256} autoComplete={mode==='signup'?'new-password':'current-password'} placeholder="At least 10 characters" required/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{mode==='signup'&&<div className="form-pair"><label>I am a<select name="role"><option value="student">Student</option><option value="teacher">Teacher</option><option value="parent">Parent</option></select></label><label>Class / area of study<input name="grade" placeholder="e.g. Class 12 · CBSE" maxLength={80}/></label></div>}{error&&<p role="alert" className="error-note">{error}</p>}<button disabled={busy} className="button button-dark button-full">{busy?'Opening your space…':mode==='signup'?'Create my space':'Log in'}<ArrowUpRight size={18}/></button></form><div className="privacy-note"><ShieldCheck size={19}/><span>Your notes and progress belong to you. Your dashboard only shows your account’s saved work.</span></div><p className="terms-note">By continuing, you agree to our <Link to="/terms-of-service">Terms</Link> and <Link to="/privacy-policy">Privacy Policy</Link>.</p></div><QuoteCard compact/><span className="account-footer">Small steps. Lasting understanding.</span></section></main>;
}
