import {useState} from 'react';
import {Sparkles,Check,CalendarDays} from 'lucide-react';
import {api} from './api';
export default function AdaptivePlanner({records,save,notify}){
 const [topics,setTopics]=useState(''),[date,setDate]=useState(''),[minutes,setMinutes]=useState(60),[busy,setBusy]=useState(false),[plan,setPlan]=useState([]);
 async function generate(e){e.preventDefault();const today=new Date().toLocaleDateString('en-CA');if(date<=today){notify('Choose an exam date after today.');return;}setBusy(true);try{const results=records.filter(r=>r.kind==='quiz-results').slice(-20).map(r=>({subject:r.data.subject||r.title,score:r.data.score}));const r=await api('/generate',{method:'POST',body:{json:true,content:JSON.stringify({topics,examDate:date,today,availableMinutesPerDay:minutes,assessmentHistory:results,existingSessions:records.filter(r=>r.kind==='planner'&&!r.data.done).map(r=>({date:r.data.date,title:r.title}))}),instruction:'Create a realistic study schedule from the supplied syllabus and assessment results. Allocate extra revision to lower scoring topics, include spaced recall and practice, and respect daily available minutes and existing sessions. Return ONLY a JSON array of at most 40 sessions with title (string), subject (string), date (YYYY-MM-DD, from today up to but before exam), minutes (integer 5–180), notes (brief study task and rationale). Do not invent scores. If no scores exist use balanced topic coverage.'}});const rows=JSON.parse(r.output);if(!Array.isArray(rows)||!rows.length||rows.some(s=>typeof s.title!=='string'||typeof s.date!=='string'||s.date<today||s.date>=date||!Number.isInteger(s.minutes)||s.minutes<5||s.minutes>180))throw new Error('The generated schedule needs another attempt. Please try again.');const totals={};for(const row of rows)totals[row.date]=(totals[row.date]||0)+row.minutes;if(Object.values(totals).some(n=>n>minutes))throw new Error('The plan exceeded your daily budget. Try fewer topics or a later exam date.');setPlan(rows);}catch(e){notify(e.message);}finally{setBusy(false);}}
 async function accept(){setBusy(true);try{for(const item of plan){await save('planner',item.title,{...item,done:false});setPlan(old=>old.filter(p=>p!==item));}notify('Your study sessions are saved.');}catch(e){notify(e.message);}finally{setBusy(false);}}
 return <section className="surface editor-panel" style={{marginBottom:28}}><div className="section-title"><div><p className="overline">A PLAN THAT LEAVES ROOM FOR LIFE</p><h3>Build your next study rhythm.</h3></div><CalendarDays/></div><p className="muted">Gemini uses your syllabus, available time, and saved assessment results to suggest a plan. Review the sessions before saving.</p><form onSubmit={generate}><label className="field">Syllabus and priorities<textarea rows={5} required value={topics} onChange={e=>setTopics(e.target.value)} placeholder="List topics, difficult concepts, and anything you need to prioritize."/></label><div className="form-pair"><label className="field">Exam date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Available minutes per day<input type="number" min="15" max="480" required value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label></div><button className="button button-dark" disabled={busy}><Sparkles size={17}/>{busy?'Building your plan…':'Plan with Gemini'}</button></form>{plan.length>0&&<div className="output-panel"><h3>Review your {plan.length} sessions</h3>{plan.map((s,i)=><div className="plan-preview-row" key={i}><span>{s.date}<small>{s.minutes} min</small></span><div><strong>{s.title}</strong><p>{s.notes}</p></div><button className="icon-button" aria-label={'Remove '+s.title} disabled={busy} onClick={()=>setPlan(plan.filter((_,n)=>n!==i))}>×</button></div>)}<button className="button button-dark" disabled={busy} onClick={accept}><Check size={17}/>Save these sessions</button></div>}</section>;
}
