import {useEffect,useState} from 'react';
import {useLocation} from 'react-router-dom';
import {Quote} from 'lucide-react';
const quotes=[
 {name:'Albert Einstein',role:'Physicist · 1879–1955',quote:'Imagination is more important than knowledge.',image:'einstein',source:'https://assets.press.princeton.edu/chapters/s10176.pdf',reference:'The Saturday Evening Post, 1929',credit:'Ferdinand Schmutzer, 1921 · Public domain',imageSource:'https://commons.wikimedia.org/wiki/File:Einstein1921_by_F_Schmutzer_2.jpg'},
 {name:'Marie Curie',role:'Physicist & chemist · 1867–1934',quote:'One never notices what has been done; one can only see what remains to be done.',image:'curie',source:'https://en.wikiquote.org/wiki/Marie_Curie',reference:'Letter to her brother, 1894',credit:'Henri Manuel, c. 1920 · Public domain',imageSource:'https://commons.wikimedia.org/wiki/File:Marie_Curie_c1920.jpg'},
 {name:'Isaac Newton',role:'Mathematician & physicist · 1643–1727',quote:'If I have seen farther, it is by standing on the shoulders of giants.',image:'newton',source:'https://newtonproject.ox.ac.uk/view/texts/normalized/OTHE00101',reference:'Letter to Robert Hooke, 1676',credit:'Godfrey Kneller, 1689 · Public domain',imageSource:'https://commons.wikimedia.org/wiki/File:GodfreyKneller-IsaacNewton-1689_(cropped).jpg'},
 {name:'Helen Keller',role:'Author & advocate · 1880–1968',quote:'Life is either a daring adventure or nothing.',image:'keller',source:'https://en.wikiquote.org/wiki/Helen_Keller',reference:'The Open Door, 1957',credit:'Unknown photographer, 1905 · Public domain',imageSource:'https://commons.wikimedia.org/wiki/File:Helen_Keller.jpg'},
 {name:'Nikola Tesla',role:'Inventor · 1856–1943',quote:'The present is theirs; the future, for which I really worked, is mine.',image:'tesla',source:'https://en.wikiquote.org/wiki/Nikola_Tesla',reference:'On his work and the future',credit:'Napoleon Sarony, c. 1890 · Public domain',imageSource:'https://commons.wikimedia.org/wiki/File:Nikola_Tesla.jpg'},
 {name:'Booker T. Washington',role:'Educator & author · 1856–1915',quote:'Success is measured by the obstacles we overcome.',image:'washington',source:'https://www.gutenberg.org/ebooks/2376',reference:'Up from Slavery, 1901',credit:'Schomburg Center portrait · Public domain',imageSource:'https://commons.wikimedia.org/wiki/File:Booker_T_Washington_portrait.jpg'},
];
const pageOffset=path=>[...path].reduce((sum,letter,index)=>sum+letter.charCodeAt(0)*(index+1),0)%quotes.length;
export default function QuoteCard({compact=false}){const {pathname}=useLocation(),[index,setIndex]=useState(()=>pageOffset(location.pathname));useEffect(()=>{setIndex(pageOffset(pathname));const timer=setInterval(()=>setIndex(current=>(current+1)%quotes.length),18000);return()=>clearInterval(timer);},[pathname]);const q=quotes[index];return <section className={'wisdom-wrap '+(compact?'wisdom-compact':'section-shell')} aria-label="Words to learn by" aria-live="polite"><div className="wisdom-card"><div className="wisdom-content"><p className="wisdom-eyebrow"><Quote size={15}/>WORDS TO LEARN BY</p><blockquote key={index}>“{q.quote}”</blockquote><div className="wisdom-person"><strong>{q.name}</strong><span>{q.role}</span><a href={q.source} target="_blank" rel="noreferrer">{q.reference} ↗</a></div><span className="wisdom-count">{String(index+1).padStart(2,'0')} / {String(quotes.length).padStart(2,'0')} · changes automatically</span></div><figure><img src={'/portraits/'+q.image+'.jpg'} alt={q.name} loading="lazy"/><figcaption><a href={q.imageSource} target="_blank" rel="noreferrer">{q.credit}</a></figcaption></figure></div></section>;}
