export const groups = ['Your workspace','Study companion','Plan & practice','Teacher studio','School & community','Growth'];
export const tools = [
 ['overview','Overview','Your learning, at a glance.','Your workspace','home'],
 ['notebooks','AI notebooks','Keep your sources close and your thinking connected.','Study companion','notebook'],
 ['tutor','Socratic tutor','Find the next question that makes everything click.','Study companion','ai'],
 ['mind-maps','Mind maps','See how your ideas connect.','Study companion','map'],
 ['flashcards','Flashcards','A little recall goes a long way.','Study companion','cards'],
 ['audio','Audio overviews','Let your next idea find you, wherever you are.','Study companion','audio'],
 ['summaries','Summary notes','The big picture, with room for the details.','Study companion','generate'],
 ['formulas','Formula sheets','Your essential equations, together.','Study companion','generate'],
 ['comparisons','Comparison tables','Understand the differences that matter.','Study companion','generate'],
 ['photo-notes','Photo to notes','Turn the board into something you can come back to.','Study companion','photo'],
 ['voice-notes','Voice notes','Speak freely. Keep the good thinking.','Study companion','voice'],
 ['planner','Study planner','A realistic rhythm for your next chapter.','Plan & practice','planner'],
 ['timetable','Timetable','Make room for class, curiosity, and rest.','Plan & practice','timetable'],
 ['homework','Homework tracker','One clear next step, before the deadline.','Plan & practice','collection'],
 ['assessments','Assessments','Practice, reflect, and understand a little more.','Plan & practice','quiz'],
 ['feedback','Essay & code feedback','Thoughtful feedback for your next draft.','Plan & practice','generate'],
 ['viva','Viva simulator','Build confidence, one spoken answer at a time.','Plan & practice','viva'],
 ['originality','Originality review','Compare passages and credit your sources.','Plan & practice','originality'],
 ['focus','Focus timer','Protect a little time for what matters.','Plan & practice','timer'],
 ['mastery','Mastery & reports','See what is growing, and what needs another visit.','Plan & practice','mastery'],
 ['lesson-plans','Lesson planner','A thoughtful starting point for every lesson.','Teacher studio','generate'],
 ['worksheets','Worksheet generator','Give every learner a way into the subject.','Teacher studio','generate'],
 ['labs','Lab instructions','From a good question to a careful experiment.','Teacher studio','generate'],
 ['resources','Resource curator','A place for the resources worth returning to.','Teacher studio','collection'],
 ['class-calendar','Class calendar','Keep the whole semester in view.','Teacher studio','collection'],
 ['class-analytics','Class analytics','Notice the learners who need a little more support.','Teacher studio','analytics'],
 ['report-comments','Report comments','Give progress the words it deserves.','Teacher studio','generate'],
 ['announcements','Announcements','Important updates, in one quiet place.','School & community','collection'],
 ['events','Events & RSVP','Make space for the moments that bring us together.','School & community','collection'],
 ['ptm','Parent meetings','A little time to talk about what matters.','School & community','collection'],
 ['fees','Fee reminders','A clear view of upcoming payments.','School & community','collection'],
 ['circulars','Circular archive','School information, easy to find again.','School & community','collection'],
 ['translations','Translate circulars','Make every family part of the conversation.','School & community','generate'],
 ['achievements','Achievement posts','Celebrate the effort behind the result.','School & community','collection'],
 ['groups','Study groups','Keep a plan for learning together.','School & community','collection'],
 ['skills','Skill navigator','Connect what you know to where you want to go.','Growth','skills'],
 ['portfolio','Portfolio builder','Give your learning something to show for itself.','Growth','collection'],
 ['badges','Badges & streaks','Small moments add up to something real.','Growth','badges'],
 ['leaderboard','Leaderboard','Your progress, at a healthy pace.','Growth','leaderboard'],
 ['settings','Your profile','Make this space feel like you.','Your workspace','settings'],
].map(([id,name,description,group,type])=>({id,name,description,group,type}));
export const prompts={
 tutor:'Tutor Socratically using only these sources. Ask one guiding question at a time. Cite source page labels when present.',
 summaries:'Create structured summary notes with headings, key concepts, examples, and a short recap, grounded only in the source.',
 formulas:'Extract equations from this material. Define variables and units and give usage conditions. Do not invent missing equations.',
 comparisons:'Build a markdown comparison table of the concepts specified, including similarities, differences, and examples.',
 feedback:'Give formative rubric feedback for the submitted essay or code: correctness, structure, logic, clarity, and actionable revisions. State limitations. Do not claim to execute code.',
 'lesson-plans':'Create a lesson plan with objectives, materials, a timed lesson flow, opening hook, practice, formative assessment, homework, support and extension.',
 worksheets:'Create a worksheet in three difficulty levels with a separate answer key. Use source content. Include MCQ, short answer and application questions.',
 labs:'Create a classroom lab guide with objectives, materials, age-appropriate safety precautions, procedure, observation table, analysis questions, and teacher review note.',
 'report-comments':'Draft respectful, specific progress comments from provided observations. Include strengths and an actionable next step. Do not invent student performance.',
 translations:'Translate this circular into the requested language, preserving dates, amounts, names and meaning.',
 skills:'Compare the learner’s current skills with their target role. Create a practical learning path with milestones, projects, and ways to demonstrate each skill. Do not invent credentials.',
 audio:'Write a spoken overview in the requested format (brief, debate, or deep dive). Ground it in the provided source. Return plain text.',
 'voice-notes':'Organize this transcript under title, key concepts, formulas, important points, doubts, and practice questions. Preserve uncertainty.',
 viva:'You are a viva examiner. Ask a focused question based on this source. If the learner answered a previous question, give constructive feedback then the next question.'
};
